# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Bunyankum' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Bunyankum
pod 'GrowingTextView'
pod 'MessageKit'
pod 'SwiftMessages'
pod 'Toast-Swift', '~> 5.0.0'
pod 'Alamofire', '~> 4.7'
pod 'AnimatedTextInput'
pod 'Kingfisher'
pod 'SideMenu'
pod 'BEMCheckBox'
pod 'DropDown'
pod 'SDWebImage/WebP'
pod 'IQKeyboardManagerSwift'
pod 'NVActivityIndicatorView'
pod 'IBAnimatable'
pod 'SkyFloatingLabelTextField', '~> 3.0'
pod "SwipeableTabBarController"
pod 'ImageSlideshow', '~> 1.6'
pod "ImageSlideshow/SDWebImage"
pod 'Cosmos', '~> 16.0'
pod 'SKPhotoBrowser'
pod 'JPVideoPlayer'
pod 'SKPhotoBrowser'
pod 'SwiftLocation'
pod "CTPanoramaView", "~> 1.3"
pod "PagingView"
pod 'DLRadioButton', '~> 1.4'
#pod "Firebase/Analytics"
pod 'Firebase/Auth'
#pod 'Firebase/Firestore'
#pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'SkeletonView'
pod 'TAPageControl'
pod 'SwiftMessages'
pod 'AdvancedPageControl'
pod 'RangeSeekSlider'
end
